version: "3"

services:
  client:
    build: ./client
    restart: always
    # volumes:
      # ./client:/usr/src/app
    ports:
      - 3000:3000
  server:
    build: ./server
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 54320:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
